server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://35.220.134.90:3306/wetalk?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: msdn
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    mode: HTML
    prefix: classpath:/templates/
  redis:
    host: 34.92.92.209
    port: 6379
    database: 1
    timeout: 5000
    password: 147852369aaa

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
